/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_derik_demo_c_third_jnitest_MyJniClass */

#ifndef _Included_com_derik_demo_c_third_jnitest_MyJniClass
#define _Included_com_derik_demo_c_third_jnitest_MyJniClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_derik_demo_c_third_jnitest_MyJniClass
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_derik_demo_c_1third_jnitest_MyJniClass_getString
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
